# site settings
title: Yamini Gaur
subtitle: Software Engineer
email: yaminigaur01@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Raleigh
state: NC
zip_code: 27609
country: United States of America


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/yamini.gaur04
github_url: https://github.com/YaminiG
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/yaminigaur/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
